#import "../template-en.typ": *

#show: doc => conf(doc)

#outline()

= Introduction

This is test for English documents.

The outline can be directly generated by `outline` as usual.

_This block is emphasized._

$ a^2 + b^2 = c^2 $

*This block is bold*

== The following paragraph will be numbered directly

#lorem(50)

#lorem(100)

== Let's continue...

$ (a^2 + b^2)(c^2 + d^2) >= ((a c)^2 + (b d)^2)^2 $

== And for math blocks...

#def(supplement: "Objects")[The content of definition.]

Normal remarks can be made here.

#def(supplement: "Category")[
    #lorem(50)
]

#def[To use lists in the block, we require:

- For markers in the bullet list
- They are in the same color as the emphcolor of the block.
- Say, blue here.

+ For numbered list we'd like to have this as well.
+ But I'm currently unaware of how to do it.
]

#thm(
    [The main theorem.], 
    proof: [It's proof here.],
    supplement: "supplements"
) <thm_ref>

#thm(
    [A theorem without proof.], 
    supplement: [supplements can be content as well]
)

#coro(
    [Counter are shared among theorems and corollaries.]
)

#lemma(
    [Lemma as well.]
)

#ex(
    [This is an exercise. To trivial to give the solution!],
    supplement: "remarks"
)

#ex(
    [Another exercise.],
    solution: [Solutions here!],
)

#rm[
    Another remark.

    #lorem(50)
]

#conj[
    Conjectures are also possible.
]

#eg(supplement: "An example")[
    We can place an example here.
]

== Now for code blocks

```rs
fn helloworld() {
    println!("helloworld!");
}
```

== Extra Functions

Use `#endofchapter()` to begin new chapter.

#endofchapter()

= With labels zeroed out

#thm(
    [Labels will be zeroed out for the new chapter.],
    proof: [See code.]
)

#endofchapter()

#show : doc => set-appendix(doc)

= An appendix here.

== Alphabetical label for the secondary headings here.

#def[
    Other items in the appendices
]

#thm[
    will have their labels zeroed out as well.
]